### PR TITLE
use refget for hashing

### PR DESCRIPTION
**Pull request by nsheff**
Can you see if this makes sense to you?

### CODE REVIEW

**Comment by nsheff** [comment]
I intend them to be functions and already started this conversion in refget, but perhaps didn't complete it.

these functions do not need the RefDB object so I've moved them off it. they are static functions.

**Comment by nsheff** [comment]
There you go, that should clean them up.

**Comment by nsheff** [comment]
If this works for you, I say we just go with this for now.

**Comment by michalstolarczyk** [comment]
ok, works. ready to merge?

**Pull request merged**
