### PR TITLE
0.4.2

### PR DESCRIPTION
**Pull request by vreuter**
- [x] https://github.com/databio/refgenconf/pull/42

### CODE REVIEW

**Comment by nsheff** [comment]
looks fine but should we bump refgenconf version to accommodate #61?

**Comment by nsheff** [comment]
I'll also do the usage docs update now... justa sec.

**Comment by vreuter** [comment]
Yeah OK let's wait for the list sorts.

**Comment by nsheff** [comment]
Ok looks good!

**Pull request merged**
